import { useEffect, useState } from 'react'
import { useAuthStore } from '@/stores/authStore'
import { supabase } from '@/lib/supabase'
import Avatar3D from '@/components/Avatar3D'
import FinancialForm from '@/components/FinancialForm'
import { getFinancialAdvice, calculateFinancialHealth, FinancialData, HealthMetrics } from '@/utils/financialHealth'
import { toast } from 'sonner'

export default function Profile() {
  const { user, setUser } = useAuthStore()
  const [loading, setLoading] = useState(false)
  const [fullName, setFullName] = useState(user?.full_name || '')
  const [fitnessLevel, setFitnessLevel] = useState(0.5)
  const [weightLevel, setWeightLevel] = useState(0.5)
  const [stressLevel, setStressLevel] = useState(0.5)
  const [happinessLevel, setHappinessLevel] = useState(0.5)
  const [bodyType, setBodyType] = useState('average')
  const [gender, setGender] = useState<'male' | 'female'>('male')
  const [showFinancialForm, setShowFinancialForm] = useState(true)
  const [financialAdvice, setFinancialAdvice] = useState<string[]>([])
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)

  useEffect(() => {
    const run = async () => {
      if (!user?.id) return
      setLoading(true)
      const { data } = await supabase
        .from('avatar_states')
        .select('*')
        .eq('user_id', user.id)
        .single()
      if (data) {
        setFitnessLevel(Number(data.fitness_level ?? 0.5))
        setWeightLevel(Number(data.weight_level ?? 0.5))
        setStressLevel(Number(data.stress_level ?? 0.5))
        setHappinessLevel(Number(data.happiness_level ?? 0.5))
        setBodyType(String(data.body_type ?? 'average'))
      }
      setLoading(false)
    }
    run()
  }, [user?.id])

  const handleFinancialAnalysis = async (data: FinancialData) => {
    setLoading(true)
    const healthMetrics = calculateFinancialHealth(data)
    const advice = getFinancialAdvice(data)
    
    // Update avatar state with calculated metrics
    setFitnessLevel(healthMetrics.fitnessLevel)
    setWeightLevel(healthMetrics.weightLevel)
    setStressLevel(healthMetrics.stressLevel)
    setHappinessLevel(healthMetrics.happinessLevel)
    setBodyType(healthMetrics.bodyType)
    setFinancialAdvice(advice)
    setIsAutoGenerated(true)
    setShowFinancialForm(false)
    
    toast.success('Financial health analyzed successfully!')
    setLoading(false)
  }

  const saveProfile = async () => {
    if (!user?.id) return
    setLoading(true)
    const { error: userErr } = await supabase.auth.updateUser({ data: { full_name: fullName } })
    if (!userErr) {
      setUser({ id: user.id, email: user.email, full_name: fullName })
    }
    const payload = {
      user_id: user.id,
      fitness_level: Number(fitnessLevel),
      weight_level: Number(weightLevel),
      stress_level: Number(stressLevel),
      happiness_level: Number(happinessLevel),
      body_type: bodyType,
      appearance_data: {
        is_auto_generated: isAutoGenerated,
        generated_at: new Date().toISOString()
      }
    }
    const { error: avatarErr } = await supabase
      .from('avatar_states')
      .upsert(payload, { onConflict: 'user_id' })
    if (userErr || avatarErr) {
      toast.error(userErr?.message || avatarErr?.message || 'Failed to save')
    } else {
      toast.success('Profile saved')
    }
    setLoading(false)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 py-10">
      <div className="container mx-auto px-4">
        <h1 className="text-3xl font-bold text-gray-800 mb-6">Profile</h1>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Account</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm text-gray-600 mb-1">Email</label>
                <input value={user?.email || ''} readOnly className="w-full bg-gray-100 text-gray-700 px-4 py-3 rounded-lg" />
              </div>
              <div>
                <label className="block text-sm text-gray-600 mb-1">Full Name</label>
                <input value={fullName} onChange={(e) => setFullName(e.target.value)} className="w-full border border-gray-300 px-4 py-3 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent" />
              </div>
            </div>
          </div>

          <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Avatar Preview</h2>
            <Avatar3D
              fitnessLevel={fitnessLevel}
              weightLevel={weightLevel}
              stressLevel={stressLevel}
              happinessLevel={happinessLevel}
              bodyType={bodyType}
              gender={gender}
            />
          </div>
        </div>

        {showFinancialForm && (
          <div className="mt-8 bg-white/80 backdrop-blur-sm rounded-2xl shadow p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Financial Health Assessment</h2>
            <p className="text-gray-600 mb-6">
              Enter your financial information to automatically generate your personalized avatar based on your financial health.
            </p>
            <FinancialForm onSubmit={handleFinancialAnalysis} loading={loading} />
          </div>
        )}

        {isAutoGenerated && (
          <div className="mt-8 bg-white/80 backdrop-blur-sm rounded-2xl shadow p-6">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-semibold text-gray-800">Financial Health Metrics</h2>
              <button
                onClick={() => setShowFinancialForm(true)}
                className="px-4 py-2 text-sm bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors"
              >
                Update Financial Data
              </button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
              <div className="bg-green-50 rounded-lg p-4">
                <h3 className="text-sm font-medium text-green-800 mb-1">Fitness Level</h3>
                <p className="text-2xl font-bold text-green-600">{Math.round(fitnessLevel * 100)}%</p>
              </div>
              <div className="bg-blue-50 rounded-lg p-4">
                <h3 className="text-sm font-medium text-blue-800 mb-1">Weight Level</h3>
                <p className="text-2xl font-bold text-blue-600">{Math.round(weightLevel * 100)}%</p>
              </div>
              <div className="bg-red-50 rounded-lg p-4">
                <h3 className="text-sm font-medium text-red-800 mb-1">Stress Level</h3>
                <p className="text-2xl font-bold text-red-600">{Math.round(stressLevel * 100)}%</p>
              </div>
              <div className="bg-yellow-50 rounded-lg p-4">
                <h3 className="text-sm font-medium text-yellow-800 mb-1">Happiness Level</h3>
                <p className="text-2xl font-bold text-yellow-600">{Math.round(happinessLevel * 100)}%</p>
              </div>
            </div>

            <div className="bg-gray-50 rounded-lg p-4">
              <h3 className="text-sm font-medium text-gray-800 mb-2">Financial Advice</h3>
              <ul className="space-y-1">
                {financialAdvice.map((advice, index) => (
                  <li key={index} className="text-sm text-gray-600 flex items-start">
                    <span className="text-purple-500 mr-2">•</span>
                    {advice}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        <div className="mt-8 bg-white/80 backdrop-blur-sm rounded-2xl shadow p-6">
          <h2 className="text-xl font-semibold text-gray-800 mb-4">Personal Characteristics</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Body Type</label>
              <select value={bodyType} onChange={(e) => setBodyType(e.target.value)} className="w-full border border-gray-300 px-4 py-3 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent">
                <option value="average">Average</option>
                <option value="fit">Fit</option>
                <option value="heavy">Heavy</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Gender</label>
              <select value={gender} onChange={(e) => setGender(e.target.value as 'male' | 'female')} className="w-full border border-gray-300 px-4 py-3 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent">
                <option value="male">Male</option>
                <option value="female">Female</option>
              </select>
            </div>
          </div>
        </div>

        <div className="mt-8 flex items-center gap-4">
          <button onClick={saveProfile} disabled={loading} className="px-6 py-3 rounded-lg bg-gradient-to-r from-purple-600 to-blue-600 text-white font-medium disabled:opacity-50">Save Changes</button>
          {loading && <span className="text-gray-600">Saving…</span>}
        </div>
      </div>
    </div>
  )
}
